### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by meirroth** [m1ga/elementor_just_free#1]
@m1ga Thanks for this plugin!
I just notices there is a notes feature that is showing, you might want to hide it with this plugin:
![image](https://user-images.githubusercontent.com/12494197/191530764-c72f8854-3df2-4d16-bc78-c43c8d7f7a8b.png)

**Comment by m1ga** [comment]
Thanks, will take a look at it :+1:

**Comment by meirroth** [comment]
@m1ga Also Custom CSS under Page Settings > Advanced, and under Site Settings > Custom CSS:
![image](https://user-images.githubusercontent.com/12494197/191548220-007b24b0-a777-4613-a465-d5adcb0e9821.png)

**Comment by m1ga** [comment]
gone: https://github.com/m1ga/elementor_just_free/releases/tag/1.2.0
